const triviaQuestions = [
    "If you could have any superpower for a day, what would it be and why?",
    "What's the weirdest food combination you actually enjoy?",
    "If our team had a theme song, what would it be?",
    "What's the most interesting place you've ever traveled to?",
    "What’s a movie or TV show you can watch over and over without getting bored?",
    "If you could swap jobs with someone for a week, who would it be?",
    "What's the funniest thing that's happened to you at work?",
    "What's a hidden talent you have that most people don’t know about?",
    "If you could instantly master any skill, what would it be?",
    "What’s your favorite bathroom song?",
    "What’s the most used emoji on your phone?",
    "What’s a hobby or activity you’ve always wanted to try but never have?",
    "If you could work from anywhere in the world for a month, where would you go?",
    "If you had to describe your work style using a meme, which one would it be?",
    "What’s one thing you appreciate most about your coworkers? \n NOTE: Don't mention anyone's name",
    "If your life had a soundtrack, what would be the first song?",
    "What’s the best piece of advice you’ve ever received?",
    "Would you rather have unlimited free coffee or free lunch for a year?",
    "Would you rather work 3 days a week but 14 hours a day, or 5 days a week but 6 hours a day?",
    "Would you rather have a boss who micromanages or a boss who is never around?",
    "Would you rather have a desk by the window or a desk next to the coffee machine?",
    "Would you rather have unlimited vacation days but no pay raises, or a big raise but no vacation days?",
    "What's the last web series/movie you watched and enjoyed it, explain the storyline?",
];

export default triviaQuestions;
